### ISSUE TITLE
"tc-admin diff" failing since ea76ecf1d3f976b1c49f5df9655905c062bb8242

### ISSUE THREAD

**Issue by marco-c** [mozilla/community-tc-config#108]
Since ea76ecf1d3f976b1c49f5df9655905c062bb8242, the task is failing with:
> RuntimeError: unmanaged resource: Role=repo:github.com/mozilla/bugbug:*

**Comment by djmitche** [comment]
fixed in bfe765cf1c20ce3581e3b47545cd07e363d71315

**Comment by djmitche** [comment]
(I think that just got missed in the flurry on Saturday)
