### ISSUE TITLE
Add a check that no roles include redundant scopes

### ISSUE THREAD

**Issue by petemoore** [mozilla/community-tc-config#137]
Sometimes we don't notice that we have directly assigned a scope to a role that it already possesses by virtue of an `assume` scope that it contains, or perhaps the list of scopes is long and we don't notice it is already included, or perhaps a `*` scope is already included which is more general, or perhaps it inherits the scope due to a parameterised role.

I would propose that if we can determine that the removal of a given scope from a role results in no change to the expanded scopes of the role, then we should fail with an error that the given scope assignment is redundant and can safely be removed.

Perhaps this is overkill, but on the other hand it might be a housekeeping aid to keep roles in check.

**Comment by djmitche** [comment]
Sounds like a good check to add to `tc-admin check` (and something that, if we get it right, cold be upstreamed into tc-admin)

**Comment by djmitche** [comment]
I don't know that this would have caught anything useful over the last year..
