### ISSUE TITLE
Remove unused secret from webrender config

### ISSUE THREAD

**Issue by staktrace** [mozilla/community-tc-config#223]
https://github.com/mozilla/community-tc-config/blob/ad04d3b692b4b46033711c0bc61790c60d0fe3e3/config/projects/webrender.yml#L31-L32

As far as I am aware, the secret referenced in this config file is not used by the WebRender setup. I think it was erroneously ported to the community TC instance and was never needed here. It was needed on the firefox TC instance, because it was needed by the WR sync task which runs in Firefox CI. So this secret can be deleted and the reference removed from the config file.

Note that since the TC split that created the community TC instance, https://hg.mozilla.org/mozilla-central/rev/03b4d21736d44c06e2aed6f52a229ba98fcebe04 also landed which renamed the secret as used on the Firefox instance. The current secret token is in `gecko/gfx-github-sync/token`, and that's the only one that needs to be kept. There is an obsolete one at `project/webrender-ci/wrupdater-github-token` that can also be deleted. I believe I can just delete that myself using the web interface but I wanted to confirm that it's not referenced in any TC config files or such before I delete it.

/cc @kvark @petemoore

**Comment by djmitche** [comment]
You'll want to make a simple PR to delete any secrets referenced in this repo, otherwise `tc-admin` runs will fail when they find the secret missing.
