### ISSUE TITLE
Requesting access to Community instance for testing

### ISSUE THREAD

**Issue by MasterWayZ** [mozilla/community-tc-config#367]
Hi,

Forwarded here from the Taskcluster channel on Matrix.

I'm really interested in Taskcluster and would like to explore it and learn it, testing things like workers and jobs. Since there are no docs yet on how to set up a Taskcluster instance yourself, I was told I could possible get access to the community instance for it, which is why I'm making this issue.

If you need any more information, please let me know.

**Comment by djmitche** [comment]
At a very basic level, you can already sign in and create a task at https://community-tc.services.mozilla.com/tasks/create -- all github users have access to the "proj-misc/tutorial" worker pool (which has pretty limited capacity).

This repository configures permissions for "projects" which are basically protected namespaces within the deployment.  You can see an example of a project for [RTEMS](https://github.com/mozilla/community-tc-config/blob/main/config/projects/rtems.yml) which was at one point interested in trying out Taskcluster (/cc @verm).  The result was that Amar got a bunch of scopes when they logged in, including scopes to create workers.  A more sophisticated project is [servo](https://github.com/mozilla/community-tc-config/blob/main/config/projects/servo.yml) which defines some worker pools and some permissions for specific github repos.

From what I understand, you're interested in experimenting with workers.  Deploying workers is necessarily a bit complicated, but maybe the best way to get you the permissions you need to do that is to set up a new project for you similar to RTEMS.  That will give you, among other things, `worker-manager:manage-worker-pool:proj-yourproject/*`, allowing you to create worker pools via the API or the UI.  What should that project be called?

**Comment by MasterWayZ** [comment]
Sounds good! I've looked into workers and I think I will need some help with it.
My general idea for this was to have a worker that I can bring myself in a VM, to run commands in a docker container. Like pulling the repo, building files and then deploying them, or even that plus having it as an artifact if that is a thing. This is just an idea I had to learn and experiment with workers and Taskcluster. One thing is that the repo is on a GitLab server, and not on GitHub. But if it's needed I can duplicate it over to GitHub. (Not sure if there's a way to get it to pull from a GitLab server)

The project name can be mwz or masterwayz, depending on what it easier to use.

**Comment by djmitche** [comment]
That sounds quite possible!  We can also create a worker pool for you that will automatically create a docker-worker instance in GCP or AWS.  But it sounds like you want to do the deployment yourself :)

The workers just run commands, so pulling from GL is not a problem.  The GitHub-specialized functionality we have is in listening for PRs and pushes and whatnot, and creating tasks in response to those.  You'd need to find a different way to approach that for GitLab.

**Comment by MasterWayZ** [comment]
I see. Well, AWS or GCP also works but whenever I make the Taskcluster deployment myself I'll bring my own instance, as I don't have the money to pay for the AWS/GCP instances.
Can it also access private GitHub repos somehow? Also, how do we continue from here?

**Comment by djmitche** [comment]
I'll update that PR to include a worker for you as well.  Once the PR's approved, we can merge and apply it and you'll have access.

Access to private GitHub repos will require that the worker has whatever credentials are required for that access.  There is a secrets service that can provide such credentials, guarded by scopes.  https://docs.taskcluster.net/docs/manual/using/secrets

**Comment by MasterWayZ** [comment]
Okay, thanks! Whenever that PR is accepted, can we take a look at it? If it's easier I can contact you on Matrix to avoid flooding this place with questions that I may get.

**Comment by djmitche** [comment]
Sure, yeah, let's chat in matrix when it's merged.
