### ISSUE TITLE
Credentials needed for community-tc pulse server

### ISSUE THREAD

**Issue by jschwartzentruber** [mozilla/community-tc-config#377]
For fuzzing tasks in community-tc, we maintain a fuzzing dashboard by scraping task status of all fuzzing hooks. Doing a full scrape takes ~15 minutes now. It would be better if we could listen to pulse messages instead.

**Comment by petemoore** [comment]
Apparently, you can create an account under https://pulseguardian.mozilla.org/ that is for firefox-ci but that server is shared with community-tc so we can manually grant you permissions to community-tc once you have the account.

**Comment by jschwartzentruber** [comment]
Great! I've created an account `fuzzing`.

**Comment by petemoore** [comment]
<img width="926" alt="Screenshot 2021-01-06 at 16 44 33" src="https://user-images.githubusercontent.com/190790/103788006-a7e61400-503e-11eb-9e11-db4024ec9d2a.png">

Hope this works! Let me know how you get on...

**Comment by petemoore** [comment]
@djmitche Anything else I need to do? Do I need to record this in an audit log or anything, so we have a record of it, or do I need to configure pulse guardian to care about cleaning up queues for this user/vhost combination etc? Or just fine as it is above?

**Comment by djmitche** [comment]
I think that's all you need to do!  This issue serves as enough of a record, hopefully (unfortunately we can't add a comment pointing to it in the pulse UI).

**Comment by jschwartzentruber** [comment]
I get this exception when I try to set `PulseConfiguration(vhost="communitytc")`

    amqp.exceptions.AccessRefused: Queue.bind: (403) ACCESS_REFUSED - access to queue 'queue/fuzzing/57584c10-503e-11eb-b284-309c23d9c56e' in vhost 'communitytc' refused for user 'fuzzing'

The same credentials work with the default vhost and show firefox-ci messages.

**Comment by djmitche** [comment]
You know that thing where you get frustrated and just randomly click on stuff?  I double-clicked on the write regexp for communitytc in the UI pictured above and lo, there's whitespace at the end of it.

I re-set the permissions to a string without whitespace.  Hopefully it's working now?

We've seen this once before.  I don't know what it is about this UI that seems to cause this issue.

**Comment by jschwartzentruber** [comment]
Progress! Now I get a more specific 403. Is it possibly the same problem in the read regexp?

    amqp.exceptions.AccessRefused: Queue.bind: (403) ACCESS_REFUSED - access to exchange 'exchange/taskcluster-queue/v1/task-defined' in vhost 'communitytc' refused for user 'fuzzing'

**Comment by djmitche** [comment]
Sorry, that was my fault -- we should probably set up some kind of automation for this :)

**Comment by djmitche** [comment]
(fixed per matrix chat)
