### ISSUE TITLE
Generate AWS region us-east-2 launch configurations

### ISSUE THREAD

**Issue by petemoore** [mozilla/community-tc-config#438]
The AWS EC2 worker pools are currently limited to regions us-east-1 / us-west-1 / us-west-2, which often results in Worker Manager failing to launch instances due to limited supply.

By adding the us-east-2 availability zones to the worker pool definitions, supply should be improved, and we should have better coverage when supply is low in the current regions. In particular, `m5.2xlarge`, which is our default instance type, is only supported in availability zones us-west-1a and us-west-1b with the currently configured regions, but is supported in many us-east-2 availability zones, so would provide a lot more coverage if us-east-2 was supported.

Note, before we add us-east-2 availability zones in the worker pool definitions, we will first need to add support for us-east-2 to the community cluster Worker Manager, which may involve ec2 configuration (e.g. creation of security groups, vpn configuration, IAM configuration, ...) and possibly additional Worker Manager configuration(?)

**Comment by jwhitlock** [comment]
The AWS, GCP, and Azure provisioners all use random sampling to pick one of the launch configurations in a pool. This may be a situation where adding more choices makes it more likely that one will fail - sending an email - but maybe be overall stable.

Would it make sense to add m4.2xlarge to the pools as well?
